name = "app"
version = "1.0.0"
gleam = ">= 0.32.0"

[dependencies]
gleam_stdlib = ">= 0.38.0 and < 1.0.0"
wisp = ">= 0.15.0 and < 1.0.0"
gleam_http = ">= 3.6.0 and < 4.0.0"
gleam_erlang = ">= 0.25.0 and < 1.0.0"
mist = ">= 1.2.0 and < 2.0.0"
gleam_json = ">= 1.0.1 and < 2.0.0"
decode = ">= 0.1.0 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
